apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-maintenance-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  fb-maintenance-page
  template:
    metadata:
      labels:
        app: fb-maintenance-page
    spec:
      containers:
      - name: fb-maintenance-page
        image: "754256621582.dkr.ecr.eu-west-2.amazonaws.com/formbuilder/fb-maintenance-page:latest"
        ports:
        - containerPort: 8080
