name: Test docker images
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  docker:
    name: Build container and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: ministryofjustice/cloud-platform-maintenance-page
          tags: latest

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: false
          load: true
          tags: ministryofjustice/cloud-platform-maintenance-page:test

      - name: Test image
        run: |
          docker run --rm --entrypoint=/bin/sh ministryofjustice/cloud-platform-maintenance-page:test -c "cat /opt/bitnami/nginx/html/index.html && ls -lash /opt/bitnami/nginx/conf/server_blocks/"
