name: Test docker images
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  docker:
    name: Build container and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0

      - name: Get Tags for Image
        id: metadata
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: ministryofjustice/cloud-platform-maintenance-page
          tags: latest

      - name: Build and push
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          context: .
          push: false
          load: true
          tags: latest

      - run: |
          docker image ls
          docker run --rm --entrypoint=/bin/sh ministryofjustice/cloud-platform-maintenance-page:latest -c "cat /opt/bitnami/nginx/html/index.html && ls -lash /opt/bitnami/nginx/conf/server_blocks/"
